<a href="https://colab.research.google.com/github/neerajvr51-hub/Medical-Insurance-Analytics/blob/main/healthcare_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as ns
import seaborn as sns

In [ ]:
df = pd.read_csv('insurance.csv')
print(df)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [ ]:
df.shape

(1338, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
df.groupby('smoker')['charges'].mean()

smoker
no      8434.268298
yes    32050.231832
Name: charges, dtype: float64

In [ ]:
high_risk = df[(df['age']>50) & (df['smoker']== 'yes')]
print(high_risk.head())

    age     sex     bmi  children smoker     region      charges
11   62  female  26.290         0    yes  southeast  27808.72510
39   60    male  39.900         0    yes  southwest  48173.36100
55   58    male  36.955         2    yes  northwest  47496.49445
58   53  female  22.880         1    yes  southeast  23244.79020
86   57  female  31.160         0    yes  northwest  43578.93940

In [ ]:
high_risk.shape

(64, 7)

In [ ]:
df.groupby('region')['charges'].mean().sort_values(ascending=False)

region
southeast    14735.411438
northeast    13406.384516
northwest    12417.575374
southwest    12346.937377
Name: charges, dtype: float64

In [ ]:
df.groupby('bmi')['charges'].mean().sort_values(ascending=True)

bmi
43.01     1149.39590
53.13     1163.46270
20.30     1242.26000
20.70     1242.81600
35.40     1263.24900
            ...
37.70    48824.45000
36.96    49577.66240
36.40    51194.55914
30.36    62592.87309
47.41    63770.42801
Name: charges, Length: 548, dtype: float64

In [ ]:
print("normal weight charges:",df[df['bmi'] < 30]['charges'].mean())

normal weight charges: 10713.666900584787

In [ ]:
print('obese charges:',df[df['bmi'] >= 30]['charges'].mean())

obese charges: 15552.335468868458

In [ ]:
df.pivot_table(index='smoker', columns=df['bmi'] >= 30, values='charges',aggfunc='mean')

bmi            False         True
smoker
no       7977.029520   8842.691548
yes     21363.217016  41557.989840