In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('healthcare_fraud_detection.csv')

In [4]:
df.head(10)

,Provider_ID,Claim_ID,Patient_Age,Patient_Gender,Diagnosis_Code,Procedure_Code,Claim_Amount,Approved_Amount,Insurance_Type,Claim_Submission_Date,Days_Between_Service_and_Claim,Number_of_Claims_Per_Provider_Monthly,Provider_Specialty,Patient_State,Claim_Status,Is_Fraud,Length_of_Stay,Visit_Type,Chronic_Condition_Flag,Prior_Visits_12m
0,P0052,C0000000,37,Male,I25.10,36415,443.51,393.16,Medicaid,01-09-2024,13,70,Cardiology,NY,Approved,0,0,Outpatient,1,2.0
1,P0121,C0000001,21,Female,E11.9,99213,467.50,461.33,Self-Pay,05-09-2022,5,62,General Practice,IL,Pending,0,5,Inpatient,1,2.0
2,P0140,C0000002,78,Female,J06.9,93000,591.69,530.06,Medicaid,11-04-2022,29,60,Cardiology,IL,Pending,0,5,Inpatient,1,3.0
3,P0202,C0000003,65,Male,I10,93000,235.15,189.11,Private,11-10-2023,22,70,General Practice,TX,Approved,0,0,Emergency,0,5.0
4,P0135,C0000004,36,Male,M54.5,85025,487.96,369.91,Private,05-09-2023,21,67,Pulmonology,PA,Approved,0,5,Inpatient,0,4.0
5,P0241,C0000005,44,Female,E11.9,80053,220.99,174.05,Medicaid,20-12-2024,26,74,Orthopedics,CA,Approved,0,2,Emergency,0,1.0
6,P0196,C0000006,50,Male,E78.5,93000,458.60,372.31,Medicare,20-02-2022,2,84,Cardiology,OH,Approved,0,0,Outpatient,1,0.0
7,P0071,C0000007,1,Male,I10,85025,934.34,321.60,NaN,13-07-2022,6,114,NaN,PA,Pending,1,2,Emergency,0,NaN
8,P0097,C0000008,34,Female,M54.5,97110,478.11,412.48,Medicare,25-05-2021,24,65,Pulmonology,IL,Pending,0,5,Inpatient,1,4.0
9,P0125,C0000009,47,Male,K21.9,99213,426.16,335.80,Self-Pay,29-05-2022,5,56,Internal Medicine,TX,Approved,0,2,Emergency,0,4.0

In [6]:
# Select object columns excluding 'Claim_ID'
categorical_cols = [col for col in df.select_dtypes(include=['object','str']).columns if col != 'Claim_ID']

# Print unique values for each categorical column
for col in categorical_cols:
    print(f"--- {col} ---")
    print(df[col].unique())
    print()

--- Provider_ID ---
<StringArray>
['P0052', 'P0121', 'P0140', 'P0202', 'P0135', 'P0241', 'P0196', 'P0071',
 'P0097', 'P0125',
 ...
 'P0006', 'P0063', 'P0043', 'P0255', 'P0236', 'P0230', 'P0156', 'P0168',
 'P0087', 'P0220']
Length: 300, dtype: str

--- Patient_Gender ---
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

--- Diagnosis_Code ---
<StringArray>
['I25.10',  'E11.9',  'J06.9',    'I10',  'M54.5',  'E78.5',  'K21.9',
  'F41.9',  'N39.0',  'J18.9']
Length: 10, dtype: str

--- Insurance_Type ---
<StringArray>
['Medicaid', 'Self-Pay', 'Private', 'Medicare', nan]
Length: 5, dtype: str

--- Claim_Submission_Date ---
<StringArray>
['01-09-2024', '05-09-2022', '11-04-2022', '11-10-2023', '05-09-2023',
 '20-12-2024', '20-02-2022', '13-07-2022', '25-05-2021', '29-05-2022',
 ...
 '23-01-2025', '29-07-2023', '02-02-2024', '13-04-2023', '12-01-2021',
 '14-05-2024', '24-10-2023', '07-02-2024', '26-01-2025', '19-04-2021']
Length: 1476, dtype: str

--- Provider_Specialty ---
<StringArray>
[       'Cardiology',  'General Practice',       'Pulmonology',
       'Orthopedics',                 nan, 'Internal Medicine',
         'Neurology']
Length: 7, dtype: str

--- Patient_State ---
<StringArray>
['NY', 'IL', 'TX', 'PA', 'CA', 'OH', 'FL', 'GA']
Length: 8, dtype: str

--- Claim_Status ---
<StringArray>
['Approved', 'Pending', 'Rejected']
Length: 3, dtype: str

--- Visit_Type ---
<StringArray>
['Outpatient', 'Inpatient', 'Emergency']
Length: 3, dtype: str

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Patient_Age,10000.0,49.755000,17.910144,1.00,37.750,50.000,62.0000,95.00
Procedure_Code,10000.0,86905.211700,14965.324960,36415.00,80053.000,93000.000,99213.0000,99214.00
Claim_Amount,10000.0,572.804406,406.202437,60.21,305.205,461.225,711.3650,6590.70
Approved_Amount,10000.0,475.514157,323.257165,50.35,257.200,388.370,598.3475,4270.89
Days_Between_Service_and_Claim,10000.0,14.413800,8.489875,0.00,7.000,14.000,22.0000,29.00
Number_of_Claims_Per_Provider_Monthly,10000.0,68.628000,14.905872,42.00,60.000,66.000,72.0000,144.00
Is_Fraud,10000.0,0.082900,0.275745,0.00,0.000,0.000,0.0000,1.00
Length_of_Stay,10000.0,2.199300,1.710460,0.00,1.000,2.000,3.0000,5.00
Chronic_Condition_Flag,10000.0,0.292000,0.454705,0.00,0.000,0.000,1.0000,1.00
Prior_Visits_12m,9650.0,3.026425,1.722789,0.00,2.000,3.000,4.0000,12.00

In [8]:
#checking whether approved amount ever exceeds claimed amount
(df["Approved_Amount"] > df["Claim_Amount"]).sum()

np.int64(0)

In [9]:
#does Claim_Amount have negative value
(df["Claim_Amount"] < 0).sum()

np.int64(0)

In [10]:
#How much percentage of 'null values' each column have
df.isna().mean() * 100

Provider_ID                              0.0
Claim_ID                                 0.0
Patient_Age                              0.0
Patient_Gender                           0.0
Diagnosis_Code                           0.0
Procedure_Code                           0.0
Claim_Amount                             0.0
Approved_Amount                          0.0
Insurance_Type                           3.5
Claim_Submission_Date                    0.0
Days_Between_Service_and_Claim           0.0
Number_of_Claims_Per_Provider_Monthly    0.0
Provider_Specialty                       3.5
Patient_State                            0.0
Claim_Status                             0.0
Is_Fraud                                 0.0
Length_of_Stay                           0.0
Visit_Type                               0.0
Chronic_Condition_Flag                   0.0
Prior_Visits_12m                         3.5
dtype: float64

In [11]:
#Replacing missing categorical data with 'Unknown'. I could have dropped these rows or imputed them with the mode, but healthcare data is highly sensitive. These missing values could correlate with fraudulent claims, so I retained them to avoid data loss.
df['Insurance_Type'] = df['Insurance_Type'].fillna('Unknown')
df['Provider_Specialty'] = df['Provider_Specialty'].fillna('Unknown')

In [12]:
#Filling this with median because visits are in count
df['Prior_Visits_12m'] = df['Prior_Visits_12m'].fillna(df['Prior_Visits_12m'].median())

In [13]:
#All null values are replaced
df.isna().sum()

Provider_ID                              0
Claim_ID                                 0
Patient_Age                              0
Patient_Gender                           0
Diagnosis_Code                           0
Procedure_Code                           0
Claim_Amount                             0
Approved_Amount                          0
Insurance_Type                           0
Claim_Submission_Date                    0
Days_Between_Service_and_Claim           0
Number_of_Claims_Per_Provider_Monthly    0
Provider_Specialty                       0
Patient_State                            0
Claim_Status                             0
Is_Fraud                                 0
Length_of_Stay                           0
Visit_Type                               0
Chronic_Condition_Flag                   0
Prior_Visits_12m                         0
dtype: int64

In [14]:
#Converting column "Claim_Submission_Date" into Datetime format
df['Claim_Submission_Date'] = pd.to_datetime(df['Claim_Submission_Date'], dayfirst=True)

In [15]:
#Extracting temporal features (Year, Month) to analyze fraudulent behavior trends,
#such as spikes before major holidays or end-of-quarter.
df['Submission_Year'] = df['Claim_Submission_Date'].dt.year
df['Submission_Month'] = df['Claim_Submission_Date'].dt.month
df['Submission_Month_Name'] = df['Claim_Submission_Date'].dt.strftime('%B')

In [16]:
#Subtracts the Approved_Amount from the Claim_Amount to know the the overbilling margin
df['Unapproved_Amount'] = df['Claim_Amount']-df['Approved_Amount']

In [17]:
df["Approval_Rate"] = (
    df["Approved_Amount"] / df["Claim_Amount"]
) * 100

In [18]:
df.columns

Index(['Provider_ID', 'Claim_ID', 'Patient_Age', 'Patient_Gender',
       'Diagnosis_Code', 'Procedure_Code', 'Claim_Amount', 'Approved_Amount',
       'Insurance_Type', 'Claim_Submission_Date',
       'Days_Between_Service_and_Claim',
       'Number_of_Claims_Per_Provider_Monthly', 'Provider_Specialty',
       'Patient_State', 'Claim_Status', 'Is_Fraud', 'Length_of_Stay',
       'Visit_Type', 'Chronic_Condition_Flag', 'Prior_Visits_12m',
       'Submission_Year', 'Submission_Month', 'Submission_Month_Name',
       'Unapproved_Amount', 'Approval_Rate'],
      dtype='str')

In [19]:
(df["Approval_Rate"] > 100).sum()

np.int64(0)

In [20]:
df.to_csv("healthcare_fraud_clean.csv", index=False)

In [21]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in C:\Users\Niraj\miniconda3\Lib\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in C:\Users\Niraj\miniconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\Users\Niraj\miniconda3\Lib\site-packages (from sqlalchemy) (3.5.4)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Niraj\miniconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
import pandas as pd
from sqlalchemy import create_engine

# Replace with your MySQL details
user = 'root'
password = 'niraj123'
host = 'localhost'
database = 'healthcare_db'

# Create connection engine
engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}/{database}")

# Save data frame to MySQL table
df.to_sql(name='healthcare_fraud', con=engine, if_exists='replace', index=False)

10000